// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OfficeTime.DBModels;

public partial class Employee
{
    public int Id { get; set; }

    public string Fio { get; set; }

    public string Telegram { get; set; }

    public string Yandex { get; set; }

    public DateTime? Datebirth { get; set; }

    public DateTime? Datestart { get; set; }

    public string Password { get; set; }

    public int Postid { get; set; }

    public virtual ICollection<Holiday> Holidays { get; set; } = new List<Holiday>();

    public virtual ICollection<Medical> Medicals { get; set; } = new List<Medical>();

    public virtual Post Post { get; set; }
}