// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OfficeTime.DBModels;

public partial class Holiday
{
    public int Id { get; set; }

    public DateTime? Datestart { get; set; }

    public DateTime? Dateend { get; set; }

    public bool? Pay { get; set; }

    public bool? Isleadapp { get; set; }

    public bool? Isdirectorapp { get; set; }

    public DateTime? Datecreate { get; set; }

    public DateTime? Dateapp { get; set; }

    public int Empid { get; set; }

    public bool? Canceled { get; set; }

    public virtual Employee Emp { get; set; }
}